# -*- coding: utf-8 -*-
"""CreditScoringModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IPIqiNDd3XY19hnL6a6PDxB0eRB29APb
"""

!pip install openpyxl
!pip install xgboost

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier

import warnings
warnings.filterwarnings('ignore')

# Plot style
plt.style.use('seaborn-v0_8')
sns.set_palette("Set2")

print("Loading data...")
train_df = pd.read_excel("C:/Users/int-winyuyu.m/Downloads/CreditScoring/Creditscore_train_set.xlsx")
test_df = pd.read_excel("C:/Users/int-winyuyu.m/Downloads/CreditScoring/Creditscore_test_set.xlsx")

print(f"Train shape: {train_df.shape}")
print(f"Test shape: {test_df.shape}")

feature_cols = [
    'Age', 'Occupation', 'Annual_Income', 'Num_Bank_Accounts', 'Num_Credit_Card',
    'Interest_Rate', 'Num_of_Loan', 'Delay_from_due_date',
    'Num_of_Delayed_Payment', 'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt',
    'Credit_Utilization_Ratio', 'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly',
    'Payment_Behaviour', 'Monthly_Balance', 'Credit_History_Age_Months'
]

X_train = train_df[feature_cols]
y_train = train_df['Credit_Score']

X_test = test_df[feature_cols]
y_test = test_df['Credit_Score']

print(f"Selected Features: {len(feature_cols)}")
print(f"X_train shape: {X_train.shape}, y_train shape: {y_train.shape}")

from sklearn.preprocessing import LabelEncoder

cat_cols = ['Occupation', 'Credit_Mix', 'Payment_of_Min_Amount', 'Payment_Behaviour']
le = LabelEncoder()

for col in cat_cols:
    # Fit and transform on both train and test to keep them consistent
    combined = pd.concat([train_df[col], test_df[col]], axis=0)
    le.fit(combined)
    train_df[col] = le.transform(train_df[col])
    test_df[col] = le.transform(test_df[col])

X_train = train_df[feature_cols]
X_test = test_df[feature_cols]

# Re-do scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Random Forest": RandomForestClassifier(random_state=42),
    "Gradient Boosting": GradientBoostingClassifier(random_state=42),
    "Support Vector Machine": SVC(probability=True),
    "K-Nearest Neighbors": KNeighborsClassifier(),
    "Naive Bayes": GaussianNB(),
    "XGBoost": XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42)
}
results = {}

for name, model in models.items():
    print(f"\n Training {name}...")

    if name in ["Logistic Regression", "Support Vector Machine", "K-Nearest Neighbors", "Naive Bayes"]:
        model.fit(X_train_scaled, y_train)
        y_pred = model.predict(X_test_scaled)
        y_proba = model.predict_proba(X_test_scaled)[:, 1]
    else:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        y_proba = model.predict_proba(X_test)[:, 1]

    acc = accuracy_score(y_test, y_pred)
    roc = roc_auc_score(y_test, y_proba)

    print(f" Accuracy: {acc:.2f}")
    print(f" ROC-AUC: {roc:.2f}")
    print("\nClassification Report:\n", classification_report(y_test, y_pred))

    # Save result inside the loop ✅
    results[name] = {
        "Accuracy": acc,
        "ROC-AUC": roc
    }

    # Confusion Matrix
    sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt='d', cmap='YlGnBu')
    plt.title(f"Confusion Matrix - {name}")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.show()

from sklearn.metrics import roc_curve, auc

plt.figure(figsize=(10, 6))
for name, model in models.items():
    if name in ["Logistic Regression", "Support Vector Machine", "K-Nearest Neighbors", "Naive Bayes"]:
        y_proba = model.predict_proba(X_test_scaled)[:, 1]
    else:
        y_proba = model.predict_proba(X_test)[:, 1]

    fpr, tpr, _ = roc_curve(y_test, y_proba)
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f"{name} (AUC = {roc_auc:.2f})")

plt.plot([0, 1], [0, 1], 'k--')
plt.title("ROC Curve Comparison")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.legend()
plt.grid()
plt.show()

importances = models["Random Forest"].feature_importances_
indices = np.argsort(importances)[::-1]
feat_names = X_train.columns

plt.figure(figsize=(10,6))
ax = sns.barplot(x=importances[indices], y=feat_names[indices])

for i, v in enumerate(importances[indices]):
    ax.text(v + 0.002, i, f'{v:.3f}', color='black', va='center')

plt.title("Features Importance - Random Forest")
plt.xlabel("Importance Score")
plt.ylabel("Feature")
plt.grid(True)
plt.tight_layout()
plt.show()

import joblib
import zipfile

# Save models
joblib.dump(models['Random Forest'], 'random_forest.pkl')
joblib.dump(models['XGBoost'], 'xgboost.pkl')

# Save preprocessing tools
joblib.dump(scaler, 'scaler.pkl')
joblib.dump(le, 'label_encoder.pkl')
# Zip all saved files
with zipfile.ZipFile('model_artifacts.zip', 'w') as zipf:
    zipf.write('random_forest.pkl')
    zipf.write('xgboost.pkl')
    zipf.write('scaler.pkl')
    zipf.write('label_encoder.pkl')

print("✅ All model files zipped!")



