# -*- coding: utf-8 -*-
"""Model_Testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N0XuRO5Amxl9FkjZT3Ez2sYA23jMy0Jb
"""

# 1. Import required libraries
import pandas as pd
import numpy as np
import joblib
from sklearn.preprocessing import LabelEncoder, StandardScaler

# 2. Load your trained model
model = joblib.load('random_forest.pkl')

# 3. Define your feature columns and categorical columns
feature_cols = [
    'Age', 'Occupation', 'Annual_Income', 'Num_Bank_Accounts', 'Num_Credit_Card',
    'Interest_Rate', 'Num_of_Loan', 'Delay_from_due_date',
    'Num_of_Delayed_Payment', 'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt',
    'Credit_Utilization_Ratio', 'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly',
    'Payment_Behaviour', 'Monthly_Balance', 'Credit_History_Age_Months'
]

cat_cols = ['Occupation', 'Credit_Mix', 'Payment_of_Min_Amount', 'Payment_Behaviour']

# 4. Input new customer data (can be a single row or multiple rows)
new_data = pd.DataFrame([{
    'Age': 24,
    'Occupation': 'Manager',
    'Annual_Income': 1650000,
    'Num_Bank_Accounts': 9,
    'Num_Credit_Card': 8,
    'Interest_Rate': 20,
    'Num_of_Loan': 4,
    'Delay_from_due_date': 29,
    'Num_of_Delayed_Payment': 1,
    'Num_Credit_Inquiries': 2,
    'Credit_Mix': 'Standard',
    'Outstanding_Debt': 350000,
    'Credit_Utilization_Ratio': 0.42,
    'Payment_of_Min_Amount': 'Yes',
    'Total_EMI_per_month': 15000,
    'Amount_invested_monthly': 3000,
    'Payment_Behaviour': 'LowspentMediumvaluepayments',
    'Monthly_Balance': 25000,
    'Credit_History_Age_Months': 49
}])

# 5. Encode categorical variables (use same order as training)
# Load label encoders from training if you saved them separately. If not, re-fit here as below:
le = LabelEncoder()
for col in cat_cols:
    combined = pd.concat([new_data[col]])  # simulate same fit
    le.fit(combined)
    new_data[col] = le.transform(new_data[col])

# 6. Scale the data (IMPORTANT: Must use the same scaler as training)
scaler = joblib.load('scaler.pkl')  # Load scaler used during training
new_data_scaled = scaler.transform(new_data[feature_cols])

# 7. Predict
prediction = model.predict(new_data_scaled)
prediction_label = 'Good' if prediction[0] == 1 else 'Bad'

print(f"Predicted Credit Score Category: {prediction_label}")

